# Common configuration.
AllCops:
  # Include common Ruby source files.
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - '.bundle/**/*'
    - 'config/**/*'
    - 'config/environments/**'
    - 'config/application.rb'
    - 'bin/**/*'
    - 'temp/**/*'
    - 'db/schema.rb'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 200
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/SymbolProc:
  Enabled: true
  Exclude:
    - app/blueprints/*
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Lint/SafeNavigationConsistency:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
